### ISSUE TITLE
UnboundLocalError: local variable 'rk_ano' referenced before assignment

### ISSUE THREAD

**Issue by BattsetsegB** [0uO/Dual-learning#1]
hi, i have question.Only for replaying the paper of Dual Learning For Machine Translation, exactly i need what configuration set?  {--dual --para } or {--dual --reinforce }? 
404line # TRAIN COMMONLY WITH PARALLEL DATA
405line      if (configs['dual']['para']):

602line  # DUAL LEARNING
603line            if configs['dual']['reinforce']:

**Comment by 0uO** [comment]
You need add
--dual
--reinforce
And --para is optional, activate it will extra use your parallel dataset ( In paper they assume this dataset is small ) to train in every epoch, commonly.

And I find this learning way will cause accumulation of noise to a certain extent, so it do not strength the ability of models. However it maybe due to my terriable codes, I guess.

**Comment by BattsetsegB** [comment]
Thanks for your reply. I tried  {--dual --joint } it's ok. But when i set  {--dual --reinforce } , it appears this error, how to handle it? My env. is GTX1070/cuda8.0/TF1.2.0.

zhen@zhen-Lenovo:~/Dual-learning/test$ ./test_train_dual.sh
...
INFO: Building model...
creating class map
loading pickle file
setting model type
loading model file
INFO: reload_filename: /home/zhen/Dual-learning/models/en2fr/model.en2fr.npz-40000
INFO: Loading model parameters from file /home/zhen/Dual-learning/models/en2fr/model.en2fr.npz-40000
INFO:tensorflow:Restoring parameters from /home/zhen/Dual-learning/models/en2fr/model.en2fr.npz-40000
INFO: Restoring parameters from /home/zhen/Dual-learning/models/en2fr/model.en2fr.npz-40000
INFO: Done
INFO: Reading data...
INFO: no validation set loaded
INFO: Done
INFO: Reading data...
INFO: no validation set loaded
INFO: Done
creating class map
loading pickle file
setting model type
loading model file
INFO: reload_filename: /home/zhen/Dual-learning/models/fr2en/model.fr2en.npz-40000
INFO: Loading model parameters from file /home/zhen/Dual-learning/models/fr2en/model.fr2en.npz-40000
INFO:tensorflow:Restoring parameters from /home/zhen/Dual-learning/models/fr2en/model.fr2en.npz-40000
INFO: Restoring parameters from /home/zhen/Dual-learning/models/fr2en/model.fr2en.npz-40000
INFO: Done
INFO: Reading data...
INFO: no validation set loaded
INFO: Done
INFO: Reading data...
INFO: no validation set loaded
INFO: Done
INFO: Initial uidx for modelA =0
INFO: Initial uidx for modelB =0
INFO: Starting epoch 0
INFO: para data has been used out at uidx0, now start using mono data. 
INFO: [2018-12-24 18:13:37] Epoch: 0 Update: 1000 MODEL:A Loss/word: -6.74628937859 Words/sec: 312.058264458 Sents/sec: 1.36458006192
Traceback (most recent call last):
  File "../nematus/nmt.py", line 1190, in <module>
    train_dual(configs)
  File "../nematus/nmt.py", line 632, in train_dual
    '[rk is pass. see nmt.py 621]', score_num[model], util.split_list(rk_ano,beam_size)[0]))
UnboundLocalError: local variable 'rk_ano' referenced before assignment

**Comment by 0uO** [comment]
Well, It obviously was a bug, and I should have already fixed it in V1.3 or V1.4. I tested it OK, try the newest version?

**Comment by BattsetsegB** [comment]
It hasn't fixed yet. i tried newest version. when download newest version, nematus/nmt.py can't  download, so i manually add. also i upgrade to  tf version 1.4 and change batch_size=4. {--dual --joint } it's ok. But {--dual --reinforce } , it appears this error again.

**Comment by 0uO** [comment]
I am sorry, It indeed hasn't been fixed until before. rk_ano here is used to count the possibility of translate back to the original sentence by another model, P(X|Yt),  and I only count it in joint training step. Now I really have fixed it. Thank you for pointing out.

**Comment by BattsetsegB** [comment]
It finally worked. :+1: 
--reload is pretrained NMT model? 
For oldest joint learning my test result 
![fr2en](https://user-images.githubusercontent.com/44496085/50416165-1ee65080-085a-11e9-8498-ff27450ff967.PNG).

**Comment by 0uO** [comment]
yes, --reload is used for reloading the pointed model for training continuously, usually the checkpoint file records the latest one's path, so just set as 'latest_checkpoint'.
